# Generated by Django 6.0.3 on 2026-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=200, verbose_name='Nombre')),
                ('tagline', models.CharField(default='...', max_length=300, verbose_name='Eslogan')),
                ('bio', models.TextField(default='...', verbose_name='Presentacion')),
                ('phone', models.CharField(default='...', max_length=50, verbose_name='Telefono')),
                ('email', models.EmailField(default='contacto@ejemplo.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='...', max_length=300, verbose_name='Direccion')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Perfil del Abogado',
                'verbose_name_plural': 'Perfil del Abogado',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('icon', models.CharField(default='⚖️', max_length=10, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'id'],
            },
        ),
    ]
